name:
channels:
- conda-forge
dependencies:
- python>=3.9,<3.11
- pip>=21.3.1
- conda>=4.11.0
- jax>=0.4.8
- psutil>=5.8.0
- numpy>=1.21.5
- matplotlib>=3.1.3
- joblib>=1.1.0
- Pillow>=9.0.1
- ipywidgets>=7.6.5    
- mediapy >= 1.1.4
- pip:
    - tensorflow-probability>=0.15.0
    - gymnasium>=0.28.1
    - optax>=0.1.2
    - brax>=0.9.1
    - flax>=0.7.2
    - dm-haiku>=0.0.10


